const axios = require("axios");

/**
 * Renders documentation as Confluence Storage Format (XHTML)
 */
function renderConfluenceMarkup(docResults) {
  const parts = [];
  const now = new Date().toLocaleString();

  parts.push(`<p><em>Generated by SnowDoc MCP · ${now}</em></p>`);
  parts.push(`<hr/>`);

  for (const doc of docResults) {
    const { filename, analysis } = doc;

    parts.push(`<h1>${escapeHtml(filename)}</h1>`);

    // Overview
    parts.push(`<h2>Overview</h2>`);
    parts.push(`<p>${escapeHtml(analysis.business_summary)}</p>`);
    parts.push(`<p>
      <strong>Complexity:</strong> ${escapeHtml(analysis.complexity)} &nbsp;|&nbsp;
      <strong>Grain:</strong> ${escapeHtml(analysis.estimated_grain)}
    </p>`);

    // Info panel for lineage
    if (analysis.lineage) {
      parts.push(`<ac:structured-macro ac:name="info">
  <ac:parameter ac:name="title">Data Lineage</ac:parameter>
  <ac:rich-text-body>
    ${analysis.lineage.target_table ? `<p><strong>Target:</strong> <code>${escapeHtml(analysis.lineage.target_table)}</code></p>` : ""}
    ${analysis.lineage.source_tables?.length ? `<p><strong>Sources:</strong> ${analysis.lineage.source_tables.map((t) => `<code>${escapeHtml(t)}</code>`).join(", ")}</p>` : ""}
    <p>${escapeHtml(analysis.lineage.transformation_summary)}</p>
  </ac:rich-text-body>
</ac:structured-macro>`);
    }

    // CTEs
    if (analysis.ctes?.length) {
      parts.push(`<h2>CTEs / Subqueries</h2>`);
      parts.push(`<table><tbody>`);
      parts.push(`<tr><th>CTE Name</th><th>Purpose</th><th>Depends On</th></tr>`);
      for (const cte of analysis.ctes) {
        parts.push(
          `<tr><td><code>${escapeHtml(cte.name)}</code></td><td>${escapeHtml(cte.purpose)}</td><td>${(cte.depends_on || []).map((d) => `<code>${escapeHtml(d)}</code>`).join(", ") || "—"}</td></tr>`
        );
      }
      parts.push(`</tbody></table>`);
    }

    // Tables referenced
    if (analysis.tables?.length) {
      parts.push(`<h2>Tables Referenced</h2>`);
      parts.push(`<table><tbody>`);
      parts.push(`<tr><th>Table</th><th>Alias</th><th>Type</th><th>Purpose</th></tr>`);
      for (const t of analysis.tables) {
        parts.push(
          `<tr><td><code>${escapeHtml(t.name)}</code></td><td>${escapeHtml(t.alias || "—")}</td><td>${escapeHtml(t.type)}</td><td>${escapeHtml(t.description)}</td></tr>`
        );
      }
      parts.push(`</tbody></table>`);
    }

    // Column dictionary
    if (analysis.columns?.length) {
      parts.push(`<h2>Column Dictionary</h2>`);
      parts.push(`<table><tbody>`);
      parts.push(`<tr><th>Column</th><th>Source</th><th>Type</th><th>Nullable</th><th>Description</th></tr>`);
      for (const col of analysis.columns) {
        parts.push(
          `<tr>
            <td><code>${col.is_key ? "🔑 " : ""}${escapeHtml(col.name)}</code></td>
            <td><code>${escapeHtml(col.source_table || "—")}</code></td>
            <td>${escapeHtml(col.data_type)}</td>
            <td>${col.nullable ? "✅" : "❌"}</td>
            <td>${escapeHtml(col.business_description)}</td>
          </tr>`
        );
      }
      parts.push(`</tbody></table>`);
    }

    // Data quality notes
    if (analysis.data_quality_notes?.length) {
      parts.push(`<h2>Data Quality Notes</h2><ul>`);
      for (const note of analysis.data_quality_notes) {
        parts.push(`<li>${escapeHtml(note)}</li>`);
      }
      parts.push(`</ul>`);
    }

    parts.push(`<hr/>`);
  }

  return parts.join("\n");
}

/**
 * Pushes documentation directly to a Confluence page via REST API
 */
async function pushToConfluence(confluenceConfig, docResults) {
  const { baseUrl, spaceKey, pageTitle, username, apiToken, parentPageId } = confluenceConfig;

  const markup = renderConfluenceMarkup(docResults);

  const auth = Buffer.from(`${username}:${apiToken}`).toString("base64");
  const headers = {
    Authorization: `Basic ${auth}`,
    "Content-Type": "application/json",
    Accept: "application/json",
  };

  // Check if page exists
  const searchUrl = `${baseUrl}/rest/api/content?title=${encodeURIComponent(pageTitle)}&spaceKey=${spaceKey}&expand=version`;
  const searchResp = await axios.get(searchUrl, { headers });

  const existing = searchResp.data.results?.[0];

  if (existing) {
    // Update existing page
    const updateUrl = `${baseUrl}/rest/api/content/${existing.id}`;
    const payload = {
      version: { number: existing.version.number + 1 },
      title: pageTitle,
      type: "page",
      body: { storage: { value: markup, representation: "storage" } },
    };
    const resp = await axios.put(updateUrl, payload, { headers });
    return { action: "updated", pageId: existing.id, url: `${baseUrl}/wiki/spaces/${spaceKey}/pages/${existing.id}` };
  } else {
    // Create new page
    const createUrl = `${baseUrl}/rest/api/content`;
    const payload = {
      type: "page",
      title: pageTitle,
      space: { key: spaceKey },
      body: { storage: { value: markup, representation: "storage" } },
      ...(parentPageId ? { ancestors: [{ id: parentPageId }] } : {}),
    };
    const resp = await axios.post(createUrl, payload, { headers });
    return { action: "created", pageId: resp.data.id, url: `${baseUrl}/wiki/spaces/${spaceKey}/pages/${resp.data.id}` };
  }
}

function escapeHtml(str) {
  if (!str) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

module.exports = { renderConfluenceMarkup, pushToConfluence };
