const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  WidthType,
  ShadingType,
  VerticalAlign,
  LevelFormat,
  PageNumber,
  Header,
  Footer,
  TabStopType,
  TabStopPosition,
} = require("docx");

const BRAND_BLUE = "1F5C9E";
const HEADER_BG = "D6E4F0";
const ROW_ALT = "F5F9FD";
const BORDER = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const BORDERS = { top: BORDER, bottom: BORDER, left: BORDER, right: BORDER };
const COL_WIDTHS = [1800, 1500, 1200, 800, 3600]; // column name, source, type, nullable, description

function headerCell(text) {
  return new TableCell({
    borders: BORDERS,
    shading: { fill: HEADER_BG, type: ShadingType.CLEAR },
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
    children: [
      new Paragraph({
        children: [new TextRun({ text, bold: true, size: 18, font: "Arial", color: "1F5C9E" })],
      }),
    ],
  });
}

function dataCell(text, width, alt = false) {
  return new TableCell({
    borders: BORDERS,
    shading: { fill: alt ? ROW_ALT : "FFFFFF", type: ShadingType.CLEAR },
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
    width: { size: width, type: WidthType.DXA },
    children: [
      new Paragraph({
        children: [new TextRun({ text: text || "—", size: 18, font: "Arial" })],
      }),
    ],
  });
}

function sectionHeading(text, level = HeadingLevel.HEADING_2) {
  return new Paragraph({
    heading: level,
    children: [new TextRun({ text, font: "Arial" })],
    spacing: { before: 240, after: 120 },
  });
}

function body(text) {
  return new Paragraph({
    children: [new TextRun({ text, size: 20, font: "Arial" })],
    spacing: { after: 120 },
  });
}

function badge(label, value) {
  return new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true, size: 18, font: "Arial", color: BRAND_BLUE }),
      new TextRun({ text: value || "—", size: 18, font: "Arial" }),
      new TextRun({ text: "   ", size: 18 }),
    ],
    spacing: { after: 80 },
  });
}

async function renderDocx(docResults) {
  const children = [];

  // Cover title
  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: "Data Documentation", font: "Arial", size: 48, bold: true, color: BRAND_BLUE })],
      spacing: { before: 480, after: 240 },
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: `Generated by SnowDoc MCP · ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
          size: 18,
          font: "Arial",
          color: "666666",
          italics: true,
        }),
      ],
      spacing: { after: 480 },
    }),
    new Paragraph({ children: [new TextRun("")], pageBreakBefore: true })
  );

  // Per-file sections
  for (const doc of docResults) {
    const { filename, analysis } = doc;

    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: filename, font: "Arial" })],
        spacing: { before: 360, after: 200 },
        border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: BRAND_BLUE, space: 1 } },
      })
    );

    // Overview
    children.push(sectionHeading("Overview"));
    children.push(body(analysis.business_summary));
    children.push(badge("Complexity", analysis.complexity));
    children.push(badge("Grain", analysis.estimated_grain));

    // Lineage
    if (analysis.lineage) {
      children.push(sectionHeading("Data Lineage"));
      if (analysis.lineage.target_table) {
        children.push(badge("Target Table", analysis.lineage.target_table));
      }
      if (analysis.lineage.source_tables?.length) {
        children.push(badge("Source Tables", analysis.lineage.source_tables.join(", ")));
      }
      children.push(body(analysis.lineage.transformation_summary));
    }

    // CTEs table
    if (analysis.ctes?.length) {
      children.push(sectionHeading("CTEs / Subqueries"));
      const cteTable = new Table({
        width: { size: 9000, type: WidthType.DXA },
        columnWidths: [2000, 4500, 2500],
        rows: [
          new TableRow({
            tableHeader: true,
            children: [
              headerCell("CTE Name"),
              headerCell("Purpose"),
              headerCell("Depends On"),
            ],
          }),
          ...analysis.ctes.map(
            (cte, i) =>
              new TableRow({
                children: [
                  dataCell(cte.name, 2000, i % 2 === 1),
                  dataCell(cte.purpose, 4500, i % 2 === 1),
                  dataCell((cte.depends_on || []).join(", "), 2500, i % 2 === 1),
                ],
              })
          ),
        ],
      });
      children.push(cteTable);
      children.push(new Paragraph({ children: [new TextRun("")], spacing: { after: 120 } }));
    }

    // Tables referenced
    if (analysis.tables?.length) {
      children.push(sectionHeading("Tables Referenced"));
      const tableRef = new Table({
        width: { size: 9000, type: WidthType.DXA },
        columnWidths: [2800, 1200, 1200, 3800],
        rows: [
          new TableRow({
            tableHeader: true,
            children: [headerCell("Table"), headerCell("Alias"), headerCell("Type"), headerCell("Purpose")],
          }),
          ...analysis.tables.map(
            (t, i) =>
              new TableRow({
                children: [
                  dataCell(t.name, 2800, i % 2 === 1),
                  dataCell(t.alias || "—", 1200, i % 2 === 1),
                  dataCell(t.type, 1200, i % 2 === 1),
                  dataCell(t.description, 3800, i % 2 === 1),
                ],
              })
          ),
        ],
      });
      children.push(tableRef);
      children.push(new Paragraph({ children: [new TextRun("")], spacing: { after: 120 } }));
    }

    // Column dictionary
    if (analysis.columns?.length) {
      children.push(sectionHeading("Column Dictionary"));
      const colTable = new Table({
        width: { size: 9360, type: WidthType.DXA },
        columnWidths: COL_WIDTHS,
        rows: [
          new TableRow({
            tableHeader: true,
            children: [
              headerCell("Column"),
              headerCell("Source"),
              headerCell("Type"),
              headerCell("Nullable"),
              headerCell("Description"),
            ],
          }),
          ...analysis.columns.map(
            (col, i) =>
              new TableRow({
                children: [
                  dataCell((col.is_key ? "🔑 " : "") + col.name, COL_WIDTHS[0], i % 2 === 1),
                  dataCell(col.source_table || "—", COL_WIDTHS[1], i % 2 === 1),
                  dataCell(col.data_type, COL_WIDTHS[2], i % 2 === 1),
                  dataCell(col.nullable ? "Yes" : "No", COL_WIDTHS[3], i % 2 === 1),
                  dataCell(col.business_description, COL_WIDTHS[4], i % 2 === 1),
                ],
              })
          ),
        ],
      });
      children.push(colTable);
      children.push(new Paragraph({ children: [new TextRun("")], spacing: { after: 120 } }));
    }

    // Data quality notes
    if (analysis.data_quality_notes?.length) {
      children.push(sectionHeading("Data Quality Notes"));
      for (const note of analysis.data_quality_notes) {
        children.push(
          new Paragraph({
            numbering: { reference: "bullets", level: 0 },
            children: [new TextRun({ text: note, size: 20, font: "Arial" })],
          })
        );
      }
      children.push(new Paragraph({ children: [new TextRun("")], spacing: { after: 120 } }));
    }
  }

  const doc = new Document({
    numbering: {
      config: [
        {
          reference: "bullets",
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: "•",
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: 720, hanging: 360 } } },
            },
          ],
        },
      ],
    },
    styles: {
      default: { document: { run: { font: "Arial", size: 20 } } },
      paragraphStyles: [
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 36, bold: true, font: "Arial", color: BRAND_BLUE },
          paragraph: { spacing: { before: 360, after: 200 }, outlineLevel: 0 },
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 26, bold: true, font: "Arial", color: "333333" },
          paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 1 },
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: 12240, height: 15840 },
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: "SnowDoc MCP — Data Documentation", size: 16, color: "888888", font: "Arial" }),
                ],
                border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: "DDDDDD", space: 1 } },
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: "Generated by SnowDoc MCP  |  Page ", size: 16, color: "888888", font: "Arial" }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: "888888", font: "Arial" }),
                  new TextRun({ text: " of ", size: 16, color: "888888", font: "Arial" }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: "888888", font: "Arial" }),
                ],
                border: { top: { style: BorderStyle.SINGLE, size: 4, color: "DDDDDD", space: 1 } },
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}

module.exports = { renderDocx };
