/**
 * Renders documentation as clean Markdown (free tier output)
 */
function renderMarkdown(docResults) {
  const lines = [];
  const now = new Date().toLocaleString();

  lines.push(`# Data Documentation`);
  lines.push(`> Generated by SnowDoc MCP · ${now}\n`);
  lines.push(`---\n`);

  // Table of contents
  lines.push(`## Table of Contents\n`);
  docResults.forEach((doc, i) => {
    const target = doc.filename.replace(/[^a-z0-9]/gi, "-").toLowerCase();
    lines.push(`${i + 1}. [${doc.filename}](#${target})`);
  });
  lines.push(``);

  // Per-file documentation
  for (const doc of docResults) {
    const { filename, analysis } = doc;
    const anchor = filename.replace(/[^a-z0-9]/gi, "-").toLowerCase();

    lines.push(`---`);
    lines.push(`## ${filename} {#${anchor}}\n`);

    // Business summary
    lines.push(`### Overview`);
    lines.push(`${analysis.business_summary}\n`);
    lines.push(`**Complexity:** ${analysis.complexity} | **Grain:** ${analysis.estimated_grain}\n`);

    // Lineage
    if (analysis.lineage) {
      lines.push(`### Data Lineage`);
      if (analysis.lineage.target_table) {
        lines.push(`**Target:** \`${analysis.lineage.target_table}\``);
      }
      if (analysis.lineage.source_tables?.length) {
        lines.push(`**Sources:** ${analysis.lineage.source_tables.map((t) => `\`${t}\``).join(", ")}`);
      }
      lines.push(`\n${analysis.lineage.transformation_summary}\n`);
    }

    // CTEs
    if (analysis.ctes?.length) {
      lines.push(`### CTEs / Subqueries`);
      lines.push(`| CTE Name | Purpose | Depends On |`);
      lines.push(`|---|---|---|`);
      for (const cte of analysis.ctes) {
        const deps = (cte.depends_on || []).join(", ") || "—";
        lines.push(`| \`${cte.name}\` | ${cte.purpose} | ${deps} |`);
      }
      lines.push(``);
    }

    // Tables
    if (analysis.tables?.length) {
      lines.push(`### Tables Referenced`);
      lines.push(`| Table | Alias | Type | Purpose |`);
      lines.push(`|---|---|---|---|`);
      for (const table of analysis.tables) {
        lines.push(
          `| \`${table.name}\` | ${table.alias || "—"} | ${table.type} | ${table.description} |`
        );
      }
      lines.push(``);
    }

    // Columns
    if (analysis.columns?.length) {
      lines.push(`### Column Dictionary`);
      lines.push(`| Column | Source | Type | Nullable | Description |`);
      lines.push(`|---|---|---|---|---|`);
      for (const col of analysis.columns) {
        const nullable = col.nullable ? "✅" : "❌";
        const key = col.is_key ? " 🔑" : "";
        lines.push(
          `| \`${col.name}\`${key} | \`${col.source_table || "—"}\` | ${col.data_type} | ${nullable} | ${col.business_description} |`
        );
      }
      lines.push(``);
    }

    // Data quality notes
    if (analysis.data_quality_notes?.length) {
      lines.push(`### Data Quality Notes`);
      for (const note of analysis.data_quality_notes) {
        lines.push(`- ${note}`);
      }
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(`*Generated by [SnowDoc MCP](https://mcpmarket.com)*`);

  return lines.join("\n");
}

module.exports = { renderMarkdown };
